// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: api/resource/export/resource_export_service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Export_ListExport_FullMethodName   = "/resource.api.resource.export.v1.Export/ListExport"
	Export_CreateExport_FullMethodName = "/resource.api.resource.export.v1.Export/CreateExport"
	Export_DeleteExport_FullMethodName = "/resource.api.resource.export.v1.Export/DeleteExport"
)

// ExportClient is the client API for Export service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExportClient interface {
	// ListExport 获取导出信息列表
	ListExport(ctx context.Context, in *ListExportRequest, opts ...grpc.CallOption) (*ListExportReply, error)
	// CreateExport 创建导出信息
	CreateExport(ctx context.Context, in *CreateExportRequest, opts ...grpc.CallOption) (*CreateExportReply, error)
	// DeleteExport 删除导出信息
	DeleteExport(ctx context.Context, in *DeleteExportRequest, opts ...grpc.CallOption) (*DeleteExportReply, error)
}

type exportClient struct {
	cc grpc.ClientConnInterface
}

func NewExportClient(cc grpc.ClientConnInterface) ExportClient {
	return &exportClient{cc}
}

func (c *exportClient) ListExport(ctx context.Context, in *ListExportRequest, opts ...grpc.CallOption) (*ListExportReply, error) {
	out := new(ListExportReply)
	err := c.cc.Invoke(ctx, Export_ListExport_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exportClient) CreateExport(ctx context.Context, in *CreateExportRequest, opts ...grpc.CallOption) (*CreateExportReply, error) {
	out := new(CreateExportReply)
	err := c.cc.Invoke(ctx, Export_CreateExport_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exportClient) DeleteExport(ctx context.Context, in *DeleteExportRequest, opts ...grpc.CallOption) (*DeleteExportReply, error) {
	out := new(DeleteExportReply)
	err := c.cc.Invoke(ctx, Export_DeleteExport_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExportServer is the server API for Export service.
// All implementations must embed UnimplementedExportServer
// for forward compatibility
type ExportServer interface {
	// ListExport 获取导出信息列表
	ListExport(context.Context, *ListExportRequest) (*ListExportReply, error)
	// CreateExport 创建导出信息
	CreateExport(context.Context, *CreateExportRequest) (*CreateExportReply, error)
	// DeleteExport 删除导出信息
	DeleteExport(context.Context, *DeleteExportRequest) (*DeleteExportReply, error)
	mustEmbedUnimplementedExportServer()
}

// UnimplementedExportServer must be embedded to have forward compatible implementations.
type UnimplementedExportServer struct {
}

func (UnimplementedExportServer) ListExport(context.Context, *ListExportRequest) (*ListExportReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListExport not implemented")
}
func (UnimplementedExportServer) CreateExport(context.Context, *CreateExportRequest) (*CreateExportReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateExport not implemented")
}
func (UnimplementedExportServer) DeleteExport(context.Context, *DeleteExportRequest) (*DeleteExportReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteExport not implemented")
}
func (UnimplementedExportServer) mustEmbedUnimplementedExportServer() {}

// UnsafeExportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExportServer will
// result in compilation errors.
type UnsafeExportServer interface {
	mustEmbedUnimplementedExportServer()
}

func RegisterExportServer(s grpc.ServiceRegistrar, srv ExportServer) {
	s.RegisterService(&Export_ServiceDesc, srv)
}

func _Export_ListExport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExportServer).ListExport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Export_ListExport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExportServer).ListExport(ctx, req.(*ListExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Export_CreateExport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExportServer).CreateExport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Export_CreateExport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExportServer).CreateExport(ctx, req.(*CreateExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Export_DeleteExport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExportServer).DeleteExport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Export_DeleteExport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExportServer).DeleteExport(ctx, req.(*DeleteExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Export_ServiceDesc is the grpc.ServiceDesc for Export service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Export_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "resource.api.resource.export.v1.Export",
	HandlerType: (*ExportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListExport",
			Handler:    _Export_ListExport_Handler,
		},
		{
			MethodName: "CreateExport",
			Handler:    _Export_CreateExport_Handler,
		},
		{
			MethodName: "DeleteExport",
			Handler:    _Export_DeleteExport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/resource/export/resource_export_service.proto",
}
