// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.24.4
// source: api/resource/export/resource_export.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetExportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  *uint32 `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Sha *string `protobuf:"bytes,2,opt,name=sha,proto3,oneof" json:"sha,omitempty"`
}

func (x *GetExportRequest) Reset() {
	*x = GetExportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_resource_export_resource_export_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExportRequest) ProtoMessage() {}

func (x *GetExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_resource_export_resource_export_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExportRequest.ProtoReflect.Descriptor instead.
func (*GetExportRequest) Descriptor() ([]byte, []int) {
	return file_api_resource_export_resource_export_proto_rawDescGZIP(), []int{0}
}

func (x *GetExportRequest) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *GetExportRequest) GetSha() string {
	if x != nil && x.Sha != nil {
		return *x.Sha
	}
	return ""
}

type GetExportReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId       uint32  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	DepartmentId uint32  `protobuf:"varint,3,opt,name=departmentId,proto3" json:"departmentId,omitempty"`
	Scene        string  `protobuf:"bytes,4,opt,name=scene,proto3" json:"scene,omitempty"`
	Name         string  `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Size         uint32  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	Sha          string  `protobuf:"bytes,7,opt,name=sha,proto3" json:"sha,omitempty"`
	Src          string  `protobuf:"bytes,8,opt,name=src,proto3" json:"src,omitempty"`
	Status       string  `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	Reason       *string `protobuf:"bytes,10,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	ExpiredAt    uint32  `protobuf:"varint,11,opt,name=expiredAt,proto3" json:"expiredAt,omitempty"`
	CreatedAt    uint32  `protobuf:"varint,12,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt    uint32  `protobuf:"varint,13,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Url          string  `protobuf:"bytes,14,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *GetExportReply) Reset() {
	*x = GetExportReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_resource_export_resource_export_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetExportReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExportReply) ProtoMessage() {}

func (x *GetExportReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_resource_export_resource_export_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExportReply.ProtoReflect.Descriptor instead.
func (*GetExportReply) Descriptor() ([]byte, []int) {
	return file_api_resource_export_resource_export_proto_rawDescGZIP(), []int{1}
}

func (x *GetExportReply) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetExportReply) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetExportReply) GetDepartmentId() uint32 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

func (x *GetExportReply) GetScene() string {
	if x != nil {
		return x.Scene
	}
	return ""
}

func (x *GetExportReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetExportReply) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetExportReply) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

func (x *GetExportReply) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *GetExportReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetExportReply) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

func (x *GetExportReply) GetExpiredAt() uint32 {
	if x != nil {
		return x.ExpiredAt
	}
	return 0
}

func (x *GetExportReply) GetCreatedAt() uint32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GetExportReply) GetUpdatedAt() uint32 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *GetExportReply) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ListExportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page          uint32   `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32   `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Order         *string  `protobuf:"bytes,3,opt,name=order,proto3,oneof" json:"order,omitempty"`
	OrderBy       *string  `protobuf:"bytes,4,opt,name=orderBy,proto3,oneof" json:"orderBy,omitempty"`
	All           bool     `protobuf:"varint,5,opt,name=all,proto3" json:"all,omitempty"`
	UserIds       []uint32 `protobuf:"varint,6,rep,packed,name=userIds,proto3" json:"userIds,omitempty"`
	DepartmentIds []uint32 `protobuf:"varint,7,rep,packed,name=departmentIds,proto3" json:"departmentIds,omitempty"`
}

func (x *ListExportRequest) Reset() {
	*x = ListExportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_resource_export_resource_export_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExportRequest) ProtoMessage() {}

func (x *ListExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_resource_export_resource_export_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExportRequest.ProtoReflect.Descriptor instead.
func (*ListExportRequest) Descriptor() ([]byte, []int) {
	return file_api_resource_export_resource_export_proto_rawDescGZIP(), []int{2}
}

func (x *ListExportRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListExportRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListExportRequest) GetOrder() string {
	if x != nil && x.Order != nil {
		return *x.Order
	}
	return ""
}

func (x *ListExportRequest) GetOrderBy() string {
	if x != nil && x.OrderBy != nil {
		return *x.OrderBy
	}
	return ""
}

func (x *ListExportRequest) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

func (x *ListExportRequest) GetUserIds() []uint32 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *ListExportRequest) GetDepartmentIds() []uint32 {
	if x != nil {
		return x.DepartmentIds
	}
	return nil
}

type ListExportReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total uint32                    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List  []*ListExportReply_Export `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ListExportReply) Reset() {
	*x = ListExportReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_resource_export_resource_export_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListExportReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExportReply) ProtoMessage() {}

func (x *ListExportReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_resource_export_resource_export_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExportReply.ProtoReflect.Descriptor instead.
func (*ListExportReply) Descriptor() ([]byte, []int) {
	return file_api_resource_export_resource_export_proto_rawDescGZIP(), []int{3}
}

func (x *ListExportReply) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListExportReply) GetList() []*ListExportReply_Export {
	if x != nil {
		return x.List
	}
	return nil
}

type ExportExcelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       uint32                           `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	DepartmentId uint32                           `protobuf:"varint,2,opt,name=departmentId,proto3" json:"departmentId,omitempty"`
	Scene        string                           `protobuf:"bytes,3,opt,name=scene,proto3" json:"scene,omitempty"`
	Name         string                           `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Headers      []string                         `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty"`
	Rows         []*ExportExcelRequest_Row        `protobuf:"bytes,6,rep,name=rows,proto3" json:"rows,omitempty"`
	Files        []*ExportExcelRequest_ExportFile `protobuf:"bytes,7,rep,name=files,proto3" json:"files,omitempty"`
}

func (x *ExportExcelRequest) Reset() {
	*x = ExportExcelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_resource_export_resource_export_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportExcelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportExcelRequest) ProtoMessage() {}

func (x *ExportExcelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_resource_export_resource_export_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportExcelRequest.ProtoReflect.Descriptor instead.
func (*ExportExcelRequest) Descriptor() ([]byte, []int) {
	return file_api_resource_export_resource_export_proto_rawDescGZIP(), []int{4}
}

func (x *ExportExcelRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ExportExcelRequest) GetDepartmentId() uint32 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

func (x *ExportExcelRequest) GetScene() string {
	if x != nil {
		return x.Scene
	}
	return ""
}

func (x *ExportExcelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExportExcelRequest) GetHeaders() []string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ExportExcelRequest) GetRows() []*ExportExcelRequest_Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *ExportExcelRequest) GetFiles() []*ExportExcelRequest_ExportFile {
	if x != nil {
		return x.Files
	}
	return nil
}

type ExportExcelReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ExportExcelReply) Reset() {
	*x = ExportExcelReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_resource_export_resource_export_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportExcelReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportExcelReply) ProtoMessage() {}

func (x *ExportExcelReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_resource_export_resource_export_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportExcelReply.ProtoReflect.Descriptor instead.
func (*ExportExcelReply) Descriptor() ([]byte, []int) {
	return file_api_resource_export_resource_export_proto_rawDescGZIP(), []int{5}
}

func (x *ExportExcelReply) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ExportFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       uint32                          `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	DepartmentId uint32                          `protobuf:"varint,2,opt,name=departmentId,proto3" json:"departmentId,omitempty"`
	Scene        string                          `protobuf:"bytes,3,opt,name=scene,proto3" json:"scene,omitempty"`
	Name         string                          `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Files        []*ExportFileRequest_ExportFile `protobuf:"bytes,5,rep,name=files,proto3" json:"files,omitempty"`
	Ids          []uint32                        `protobuf:"varint,6,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *ExportFileRequest) Reset() {
	*x = ExportFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_resource_export_resource_export_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportFileRequest) ProtoMessage() {}

func (x *ExportFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_resource_export_resource_export_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportFileRequest.ProtoReflect.Descriptor instead.
func (*ExportFileRequest) Descriptor() ([]byte, []int) {
	return file_api_resource_export_resource_export_proto_rawDescGZIP(), []int{6}
}

func (x *ExportFileRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ExportFileRequest) GetDepartmentId() uint32 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

func (x *ExportFileRequest) GetScene() string {
	if x != nil {
		return x.Scene
	}
	return ""
}

func (x *ExportFileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExportFileRequest) GetFiles() []*ExportFileRequest_ExportFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ExportFileRequest) GetIds() []uint32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ExportFileReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ExportFileReply) Reset() {
	*x = ExportFileReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_resource_export_resource_export_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportFileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportFileReply) ProtoMessage() {}

func (x *ExportFileReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_resource_export_resource_export_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportFileReply.ProtoReflect.Descriptor instead.
func (*ExportFileReply) Descriptor() ([]byte, []int) {
	return file_api_resource_export_resource_export_proto_rawDescGZIP(), []int{7}
}

func (x *ExportFileReply) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteExportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []uint32 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *DeleteExportRequest) Reset() {
	*x = DeleteExportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_resource_export_resource_export_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExportRequest) ProtoMessage() {}

func (x *DeleteExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_resource_export_resource_export_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExportRequest.ProtoReflect.Descriptor instead.
func (*DeleteExportRequest) Descriptor() ([]byte, []int) {
	return file_api_resource_export_resource_export_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteExportRequest) GetIds() []uint32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteExportReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total uint32 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *DeleteExportReply) Reset() {
	*x = DeleteExportReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_resource_export_resource_export_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteExportReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExportReply) ProtoMessage() {}

func (x *DeleteExportReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_resource_export_resource_export_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExportReply.ProtoReflect.Descriptor instead.
func (*DeleteExportReply) Descriptor() ([]byte, []int) {
	return file_api_resource_export_resource_export_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteExportReply) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListExportReply_Export struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId       uint32  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	DepartmentId uint32  `protobuf:"varint,3,opt,name=departmentId,proto3" json:"departmentId,omitempty"`
	Scene        string  `protobuf:"bytes,4,opt,name=scene,proto3" json:"scene,omitempty"`
	Name         string  `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Size         uint32  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	Sha          string  `protobuf:"bytes,7,opt,name=sha,proto3" json:"sha,omitempty"`
	Src          string  `protobuf:"bytes,8,opt,name=src,proto3" json:"src,omitempty"`
	Status       string  `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	Reason       *string `protobuf:"bytes,10,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	ExpiredAt    uint32  `protobuf:"varint,11,opt,name=expiredAt,proto3" json:"expiredAt,omitempty"`
	CreatedAt    uint32  `protobuf:"varint,12,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt    uint32  `protobuf:"varint,13,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Url          string  `protobuf:"bytes,14,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *ListExportReply_Export) Reset() {
	*x = ListExportReply_Export{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_resource_export_resource_export_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListExportReply_Export) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExportReply_Export) ProtoMessage() {}

func (x *ListExportReply_Export) ProtoReflect() protoreflect.Message {
	mi := &file_api_resource_export_resource_export_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExportReply_Export.ProtoReflect.Descriptor instead.
func (*ListExportReply_Export) Descriptor() ([]byte, []int) {
	return file_api_resource_export_resource_export_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ListExportReply_Export) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListExportReply_Export) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListExportReply_Export) GetDepartmentId() uint32 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

func (x *ListExportReply_Export) GetScene() string {
	if x != nil {
		return x.Scene
	}
	return ""
}

func (x *ListExportReply_Export) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListExportReply_Export) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListExportReply_Export) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

func (x *ListExportReply_Export) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *ListExportReply_Export) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListExportReply_Export) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

func (x *ListExportReply_Export) GetExpiredAt() uint32 {
	if x != nil {
		return x.ExpiredAt
	}
	return 0
}

func (x *ListExportReply_Export) GetCreatedAt() uint32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ListExportReply_Export) GetUpdatedAt() uint32 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ListExportReply_Export) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ExportExcelRequest_Col struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ExportExcelRequest_Col) Reset() {
	*x = ExportExcelRequest_Col{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_resource_export_resource_export_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportExcelRequest_Col) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportExcelRequest_Col) ProtoMessage() {}

func (x *ExportExcelRequest_Col) ProtoReflect() protoreflect.Message {
	mi := &file_api_resource_export_resource_export_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportExcelRequest_Col.ProtoReflect.Descriptor instead.
func (*ExportExcelRequest_Col) Descriptor() ([]byte, []int) {
	return file_api_resource_export_resource_export_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ExportExcelRequest_Col) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ExportExcelRequest_Col) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ExportExcelRequest_Row struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cols []*ExportExcelRequest_Col `protobuf:"bytes,1,rep,name=cols,proto3" json:"cols,omitempty"`
}

func (x *ExportExcelRequest_Row) Reset() {
	*x = ExportExcelRequest_Row{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_resource_export_resource_export_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportExcelRequest_Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportExcelRequest_Row) ProtoMessage() {}

func (x *ExportExcelRequest_Row) ProtoReflect() protoreflect.Message {
	mi := &file_api_resource_export_resource_export_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportExcelRequest_Row.ProtoReflect.Descriptor instead.
func (*ExportExcelRequest_Row) Descriptor() ([]byte, []int) {
	return file_api_resource_export_resource_export_proto_rawDescGZIP(), []int{4, 1}
}

func (x *ExportExcelRequest_Row) GetCols() []*ExportExcelRequest_Col {
	if x != nil {
		return x.Cols
	}
	return nil
}

type ExportExcelRequest_ExportFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value  string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Rename string `protobuf:"bytes,2,opt,name=rename,proto3" json:"rename,omitempty"`
}

func (x *ExportExcelRequest_ExportFile) Reset() {
	*x = ExportExcelRequest_ExportFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_resource_export_resource_export_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportExcelRequest_ExportFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportExcelRequest_ExportFile) ProtoMessage() {}

func (x *ExportExcelRequest_ExportFile) ProtoReflect() protoreflect.Message {
	mi := &file_api_resource_export_resource_export_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportExcelRequest_ExportFile.ProtoReflect.Descriptor instead.
func (*ExportExcelRequest_ExportFile) Descriptor() ([]byte, []int) {
	return file_api_resource_export_resource_export_proto_rawDescGZIP(), []int{4, 2}
}

func (x *ExportExcelRequest_ExportFile) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ExportExcelRequest_ExportFile) GetRename() string {
	if x != nil {
		return x.Rename
	}
	return ""
}

type ExportFileRequest_ExportFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value  string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Rename string `protobuf:"bytes,2,opt,name=rename,proto3" json:"rename,omitempty"`
}

func (x *ExportFileRequest_ExportFile) Reset() {
	*x = ExportFileRequest_ExportFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_resource_export_resource_export_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportFileRequest_ExportFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportFileRequest_ExportFile) ProtoMessage() {}

func (x *ExportFileRequest_ExportFile) ProtoReflect() protoreflect.Message {
	mi := &file_api_resource_export_resource_export_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportFileRequest_ExportFile.ProtoReflect.Descriptor instead.
func (*ExportFileRequest_ExportFile) Descriptor() ([]byte, []int) {
	return file_api_resource_export_resource_export_proto_rawDescGZIP(), []int{6, 0}
}

func (x *ExportFileRequest_ExportFile) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ExportFileRequest_ExportFile) GetRename() string {
	if x != nil {
		return x.Rename
	}
	return ""
}

var File_api_resource_export_resource_export_proto protoreflect.FileDescriptor

var file_api_resource_export_resource_export_proto_rawDesc = []byte{
	0x0a, 0x29, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2f, 0x65,
	0x78, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x65,
	0x78, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1f, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x2e, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x17, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x56, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x45, 0x78, 0x70, 0x6f,
	0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x20, 0x00, 0x48, 0x00,
	0x52, 0x02, 0x69, 0x64, 0x88, 0x01, 0x01, 0x12, 0x15, 0x0a, 0x03, 0x73, 0x68, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x03, 0x73, 0x68, 0x61, 0x88, 0x01, 0x01, 0x42, 0x05,
	0x0a, 0x03, 0x5f, 0x69, 0x64, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x73, 0x68, 0x61, 0x22, 0xea, 0x02,
	0x0a, 0x0e, 0x47, 0x65, 0x74, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x70, 0x61,
	0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c,
	0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x63, 0x65, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x63, 0x65,
	0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x68,
	0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x68, 0x61, 0x12, 0x10, 0x0a, 0x03,
	0x73, 0x72, 0x63, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x72, 0x63, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x88, 0x01, 0x01, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x41, 0x74,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x72, 0x6c, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x42,
	0x09, 0x0a, 0x07, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0xae, 0x02, 0x0a, 0x11, 0x4c,
	0x69, 0x73, 0x74, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07,
	0xfa, 0x42, 0x04, 0x2a, 0x02, 0x20, 0x00, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x25, 0x0a,
	0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x42,
	0x09, 0xfa, 0x42, 0x06, 0x2a, 0x04, 0x18, 0x32, 0x20, 0x00, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x10, 0xfa, 0x42, 0x0d, 0x72, 0x0b, 0x52, 0x03, 0x61, 0x73, 0x63, 0x52,
	0x04, 0x64, 0x65, 0x73, 0x63, 0x48, 0x00, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x88, 0x01,
	0x01, 0x12, 0x40, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x21, 0xfa, 0x42, 0x1e, 0x72, 0x1c, 0x52, 0x02, 0x69, 0x64, 0x52, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x48, 0x01, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79,
	0x88, 0x01, 0x01, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x6c, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x03, 0x61, 0x6c, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x12,
	0x24, 0x0a, 0x0d, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x73,
	0x18, 0x07, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0d, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x73, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x42,
	0x0a, 0x0a, 0x08, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x22, 0xd9, 0x03, 0x0a, 0x0f,
	0x4c, 0x69, 0x73, 0x74, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x4b, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x65, 0x78, 0x70, 0x6f,
	0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x1a, 0xe2, 0x02, 0x0a, 0x06, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x64, 0x65, 0x70,
	0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x65,
	0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x68, 0x61, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x68, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x72, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x88, 0x01, 0x01,
	0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x41, 0x74, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x42, 0x09, 0x0a, 0x07,
	0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0xb9, 0x04, 0x0a, 0x12, 0x45, 0x78, 0x70, 0x6f,
	0x72, 0x74, 0x45, 0x78, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07,
	0xfa, 0x42, 0x04, 0x2a, 0x02, 0x20, 0x00, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x2b, 0x0a, 0x0c, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x20, 0x00, 0x52, 0x0c,
	0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x05,
	0x73, 0x63, 0x65, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04,
	0x72, 0x02, 0x10, 0x01, 0x52, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x12, 0x1b, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02,
	0x10, 0x01, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x92, 0x01,
	0x02, 0x08, 0x01, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x55, 0x0a, 0x04,
	0x72, 0x6f, 0x77, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x2e, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x70,
	0x6f, 0x72, 0x74, 0x45, 0x78, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x52, 0x6f, 0x77, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x92, 0x01, 0x02, 0x08, 0x01, 0x52, 0x04, 0x72,
	0x6f, 0x77, 0x73, 0x12, 0x54, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x3e, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x65, 0x78, 0x70, 0x6f, 0x72,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x45, 0x78, 0x63, 0x65, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x46, 0x69,
	0x6c, 0x65, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x1a, 0x38, 0x0a, 0x03, 0x43, 0x6f, 0x6c,
	0x12, 0x1b, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07,
	0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x1a, 0x52, 0x0a, 0x03, 0x52, 0x6f, 0x77, 0x12, 0x4b, 0x0a, 0x04, 0x63, 0x6f,
	0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x2e, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x72,
	0x74, 0x45, 0x78, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x6f,
	0x6c, 0x52, 0x04, 0x63, 0x6f, 0x6c, 0x73, 0x1a, 0x3a, 0x0a, 0x0a, 0x45, 0x78, 0x70, 0x6f, 0x72,
	0x74, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x22, 0x0a, 0x10, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x45, 0x78, 0x63,
	0x65, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0xc0, 0x02, 0x0a, 0x11, 0x45, 0x78, 0x70, 0x6f,
	0x72, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa,
	0x42, 0x04, 0x2a, 0x02, 0x20, 0x00, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2b,
	0x0a, 0x0c, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x20, 0x00, 0x52, 0x0c, 0x64,
	0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x05, 0x73,
	0x63, 0x65, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72,
	0x02, 0x10, 0x01, 0x52, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x12, 0x1b, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10,
	0x01, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x53, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3d, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x65,
	0x78, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x46,
	0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x72,
	0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x69, 0x64, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x03, 0x69, 0x64, 0x73, 0x1a, 0x3a,
	0x0a, 0x0a, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x21, 0x0a, 0x0f, 0x45, 0x78,
	0x70, 0x6f, 0x72, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x35, 0x0a,
	0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0d, 0x42, 0x0c, 0xfa, 0x42, 0x09, 0x92, 0x01, 0x06, 0x08, 0x01, 0x10, 0x32, 0x18, 0x01, 0x52,
	0x03, 0x69, 0x64, 0x73, 0x22, 0x29, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x78,
	0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x42,
	0x36, 0x0a, 0x1f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x2e,
	0x76, 0x31, 0x42, 0x08, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x56, 0x31, 0x50, 0x01, 0x5a, 0x07,
	0x2e, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_resource_export_resource_export_proto_rawDescOnce sync.Once
	file_api_resource_export_resource_export_proto_rawDescData = file_api_resource_export_resource_export_proto_rawDesc
)

func file_api_resource_export_resource_export_proto_rawDescGZIP() []byte {
	file_api_resource_export_resource_export_proto_rawDescOnce.Do(func() {
		file_api_resource_export_resource_export_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_resource_export_resource_export_proto_rawDescData)
	})
	return file_api_resource_export_resource_export_proto_rawDescData
}

var file_api_resource_export_resource_export_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_resource_export_resource_export_proto_goTypes = []interface{}{
	(*GetExportRequest)(nil),              // 0: resource.api.resource.export.v1.GetExportRequest
	(*GetExportReply)(nil),                // 1: resource.api.resource.export.v1.GetExportReply
	(*ListExportRequest)(nil),             // 2: resource.api.resource.export.v1.ListExportRequest
	(*ListExportReply)(nil),               // 3: resource.api.resource.export.v1.ListExportReply
	(*ExportExcelRequest)(nil),            // 4: resource.api.resource.export.v1.ExportExcelRequest
	(*ExportExcelReply)(nil),              // 5: resource.api.resource.export.v1.ExportExcelReply
	(*ExportFileRequest)(nil),             // 6: resource.api.resource.export.v1.ExportFileRequest
	(*ExportFileReply)(nil),               // 7: resource.api.resource.export.v1.ExportFileReply
	(*DeleteExportRequest)(nil),           // 8: resource.api.resource.export.v1.DeleteExportRequest
	(*DeleteExportReply)(nil),             // 9: resource.api.resource.export.v1.DeleteExportReply
	(*ListExportReply_Export)(nil),        // 10: resource.api.resource.export.v1.ListExportReply.Export
	(*ExportExcelRequest_Col)(nil),        // 11: resource.api.resource.export.v1.ExportExcelRequest.Col
	(*ExportExcelRequest_Row)(nil),        // 12: resource.api.resource.export.v1.ExportExcelRequest.Row
	(*ExportExcelRequest_ExportFile)(nil), // 13: resource.api.resource.export.v1.ExportExcelRequest.ExportFile
	(*ExportFileRequest_ExportFile)(nil),  // 14: resource.api.resource.export.v1.ExportFileRequest.ExportFile
}
var file_api_resource_export_resource_export_proto_depIdxs = []int32{
	10, // 0: resource.api.resource.export.v1.ListExportReply.list:type_name -> resource.api.resource.export.v1.ListExportReply.Export
	12, // 1: resource.api.resource.export.v1.ExportExcelRequest.rows:type_name -> resource.api.resource.export.v1.ExportExcelRequest.Row
	13, // 2: resource.api.resource.export.v1.ExportExcelRequest.files:type_name -> resource.api.resource.export.v1.ExportExcelRequest.ExportFile
	14, // 3: resource.api.resource.export.v1.ExportFileRequest.files:type_name -> resource.api.resource.export.v1.ExportFileRequest.ExportFile
	11, // 4: resource.api.resource.export.v1.ExportExcelRequest.Row.cols:type_name -> resource.api.resource.export.v1.ExportExcelRequest.Col
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_resource_export_resource_export_proto_init() }
func file_api_resource_export_resource_export_proto_init() {
	if File_api_resource_export_resource_export_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_resource_export_resource_export_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetExportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_resource_export_resource_export_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetExportReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_resource_export_resource_export_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListExportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_resource_export_resource_export_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListExportReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_resource_export_resource_export_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportExcelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_resource_export_resource_export_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportExcelReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_resource_export_resource_export_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_resource_export_resource_export_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportFileReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_resource_export_resource_export_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteExportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_resource_export_resource_export_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteExportReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_resource_export_resource_export_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListExportReply_Export); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_resource_export_resource_export_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportExcelRequest_Col); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_resource_export_resource_export_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportExcelRequest_Row); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_resource_export_resource_export_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportExcelRequest_ExportFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_resource_export_resource_export_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportFileRequest_ExportFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_resource_export_resource_export_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_api_resource_export_resource_export_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_api_resource_export_resource_export_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_api_resource_export_resource_export_proto_msgTypes[10].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_resource_export_resource_export_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_resource_export_resource_export_proto_goTypes,
		DependencyIndexes: file_api_resource_export_resource_export_proto_depIdxs,
		MessageInfos:      file_api_resource_export_resource_export_proto_msgTypes,
	}.Build()
	File_api_resource_export_resource_export_proto = out.File
	file_api_resource_export_resource_export_proto_rawDesc = nil
	file_api_resource_export_resource_export_proto_goTypes = nil
	file_api_resource_export_resource_export_proto_depIdxs = nil
}
