// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: resource_file.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on File with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *File) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on File with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in FileMultiError, or nil if none found.
func (m *File) ValidateAll() error {
	return m.validate(true)
}

func (m *File) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for DirectoryId

	// no validation rules for Name

	// no validation rules for Type

	// no validation rules for Size

	// no validation rules for Sha

	// no validation rules for Src

	// no validation rules for Storage

	// no validation rules for CreatedAt

	if len(errors) > 0 {
		return FileMultiError(errors)
	}

	return nil
}

// FileMultiError is an error wrapping multiple validation errors returned by
// File.ValidateAll() if the designated constraints aren't met.
type FileMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FileMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FileMultiError) AllErrors() []error { return m }

// FileValidationError is the validation error returned by File.Validate if the
// designated constraints aren't met.
type FileValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FileValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FileValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FileValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FileValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FileValidationError) ErrorName() string { return "FileValidationError" }

// Error satisfies the builtin error interface
func (e FileValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFile.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FileValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FileValidationError{}

// Validate checks the field values on GetFileRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetFileRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetFileRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetFileRequestMultiError,
// or nil if none found.
func (m *GetFileRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetFileRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetSrc()) < 1 {
		err := GetFileRequestValidationError{
			field:  "Src",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Width

	// no validation rules for Height

	// no validation rules for Mode

	// no validation rules for IsRange

	// no validation rules for Start

	// no validation rules for End

	if len(errors) > 0 {
		return GetFileRequestMultiError(errors)
	}

	return nil
}

// GetFileRequestMultiError is an error wrapping multiple validation errors
// returned by GetFileRequest.ValidateAll() if the designated constraints
// aren't met.
type GetFileRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetFileRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetFileRequestMultiError) AllErrors() []error { return m }

// GetFileRequestValidationError is the validation error returned by
// GetFileRequest.Validate if the designated constraints aren't met.
type GetFileRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetFileRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetFileRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetFileRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetFileRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetFileRequestValidationError) ErrorName() string { return "GetFileRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetFileRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetFileRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetFileRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetFileRequestValidationError{}

// Validate checks the field values on GetFileReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetFileReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetFileReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetFileReplyMultiError, or
// nil if none found.
func (m *GetFileReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetFileReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Data

	// no validation rules for Mime

	if len(errors) > 0 {
		return GetFileReplyMultiError(errors)
	}

	return nil
}

// GetFileReplyMultiError is an error wrapping multiple validation errors
// returned by GetFileReply.ValidateAll() if the designated constraints aren't met.
type GetFileReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetFileReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetFileReplyMultiError) AllErrors() []error { return m }

// GetFileReplyValidationError is the validation error returned by
// GetFileReply.Validate if the designated constraints aren't met.
type GetFileReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetFileReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetFileReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetFileReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetFileReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetFileReplyValidationError) ErrorName() string { return "GetFileReplyValidationError" }

// Error satisfies the builtin error interface
func (e GetFileReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetFileReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetFileReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetFileReplyValidationError{}

// Validate checks the field values on GetFileByShaRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetFileByShaRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetFileByShaRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetFileByShaRequestMultiError, or nil if none found.
func (m *GetFileByShaRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetFileByShaRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetSha()) < 1 {
		err := GetFileByShaRequestValidationError{
			field:  "Sha",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetFileByShaRequestMultiError(errors)
	}

	return nil
}

// GetFileByShaRequestMultiError is an error wrapping multiple validation
// errors returned by GetFileByShaRequest.ValidateAll() if the designated
// constraints aren't met.
type GetFileByShaRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetFileByShaRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetFileByShaRequestMultiError) AllErrors() []error { return m }

// GetFileByShaRequestValidationError is the validation error returned by
// GetFileByShaRequest.Validate if the designated constraints aren't met.
type GetFileByShaRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetFileByShaRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetFileByShaRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetFileByShaRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetFileByShaRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetFileByShaRequestValidationError) ErrorName() string {
	return "GetFileByShaRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetFileByShaRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetFileByShaRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetFileByShaRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetFileByShaRequestValidationError{}

// Validate checks the field values on PrepareUploadFileRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PrepareUploadFileRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PrepareUploadFileRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PrepareUploadFileRequestMultiError, or nil if none found.
func (m *PrepareUploadFileRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PrepareUploadFileRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DirectoryId

	// no validation rules for DirectoryPath

	if utf8.RuneCountInString(m.GetApp()) < 1 {
		err := PrepareUploadFileRequestValidationError{
			field:  "App",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := PrepareUploadFileRequestValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetSha()) < 1 {
		err := PrepareUploadFileRequestValidationError{
			field:  "Sha",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetSize() <= 0 {
		err := PrepareUploadFileRequestValidationError{
			field:  "Size",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return PrepareUploadFileRequestMultiError(errors)
	}

	return nil
}

// PrepareUploadFileRequestMultiError is an error wrapping multiple validation
// errors returned by PrepareUploadFileRequest.ValidateAll() if the designated
// constraints aren't met.
type PrepareUploadFileRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PrepareUploadFileRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PrepareUploadFileRequestMultiError) AllErrors() []error { return m }

// PrepareUploadFileRequestValidationError is the validation error returned by
// PrepareUploadFileRequest.Validate if the designated constraints aren't met.
type PrepareUploadFileRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PrepareUploadFileRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PrepareUploadFileRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PrepareUploadFileRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PrepareUploadFileRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PrepareUploadFileRequestValidationError) ErrorName() string {
	return "PrepareUploadFileRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PrepareUploadFileRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPrepareUploadFileRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PrepareUploadFileRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PrepareUploadFileRequestValidationError{}

// Validate checks the field values on PrepareUploadFileReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PrepareUploadFileReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PrepareUploadFileReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PrepareUploadFileReplyMultiError, or nil if none found.
func (m *PrepareUploadFileReply) ValidateAll() error {
	return m.validate(true)
}

func (m *PrepareUploadFileReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Uploaded != nil {
		// no validation rules for Uploaded
	}

	if m.Src != nil {
		// no validation rules for Src
	}

	if m.ChunkSize != nil {
		// no validation rules for ChunkSize
	}

	if m.ChunkCount != nil {
		// no validation rules for ChunkCount
	}

	if m.UploadId != nil {
		// no validation rules for UploadId
	}

	if m.Sha != nil {
		// no validation rules for Sha
	}

	if len(errors) > 0 {
		return PrepareUploadFileReplyMultiError(errors)
	}

	return nil
}

// PrepareUploadFileReplyMultiError is an error wrapping multiple validation
// errors returned by PrepareUploadFileReply.ValidateAll() if the designated
// constraints aren't met.
type PrepareUploadFileReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PrepareUploadFileReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PrepareUploadFileReplyMultiError) AllErrors() []error { return m }

// PrepareUploadFileReplyValidationError is the validation error returned by
// PrepareUploadFileReply.Validate if the designated constraints aren't met.
type PrepareUploadFileReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PrepareUploadFileReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PrepareUploadFileReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PrepareUploadFileReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PrepareUploadFileReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PrepareUploadFileReplyValidationError) ErrorName() string {
	return "PrepareUploadFileReplyValidationError"
}

// Error satisfies the builtin error interface
func (e PrepareUploadFileReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPrepareUploadFileReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PrepareUploadFileReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PrepareUploadFileReplyValidationError{}

// Validate checks the field values on PageFileRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PageFileRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PageFileRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PageFileRequestMultiError, or nil if none found.
func (m *PageFileRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PageFileRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetDirectoryId() <= 0 {
		err := PageFileRequestValidationError{
			field:  "DirectoryId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetApp()) < 1 {
		err := PageFileRequestValidationError{
			field:  "App",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetPage() <= 0 {
		err := PageFileRequestValidationError{
			field:  "Page",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetPageSize(); val <= 0 || val > 100 {
		err := PageFileRequestValidationError{
			field:  "PageSize",
			reason: "value must be inside range (0, 100]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.Name != nil {
		// no validation rules for Name
	}

	if len(errors) > 0 {
		return PageFileRequestMultiError(errors)
	}

	return nil
}

// PageFileRequestMultiError is an error wrapping multiple validation errors
// returned by PageFileRequest.ValidateAll() if the designated constraints
// aren't met.
type PageFileRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PageFileRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PageFileRequestMultiError) AllErrors() []error { return m }

// PageFileRequestValidationError is the validation error returned by
// PageFileRequest.Validate if the designated constraints aren't met.
type PageFileRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PageFileRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PageFileRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PageFileRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PageFileRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PageFileRequestValidationError) ErrorName() string { return "PageFileRequestValidationError" }

// Error satisfies the builtin error interface
func (e PageFileRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPageFileRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PageFileRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PageFileRequestValidationError{}

// Validate checks the field values on PageFileReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PageFileReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PageFileReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PageFileReplyMultiError, or
// nil if none found.
func (m *PageFileReply) ValidateAll() error {
	return m.validate(true)
}

func (m *PageFileReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PageFileReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PageFileReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PageFileReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Total != nil {
		// no validation rules for Total
	}

	if len(errors) > 0 {
		return PageFileReplyMultiError(errors)
	}

	return nil
}

// PageFileReplyMultiError is an error wrapping multiple validation errors
// returned by PageFileReply.ValidateAll() if the designated constraints
// aren't met.
type PageFileReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PageFileReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PageFileReplyMultiError) AllErrors() []error { return m }

// PageFileReplyValidationError is the validation error returned by
// PageFileReply.Validate if the designated constraints aren't met.
type PageFileReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PageFileReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PageFileReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PageFileReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PageFileReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PageFileReplyValidationError) ErrorName() string { return "PageFileReplyValidationError" }

// Error satisfies the builtin error interface
func (e PageFileReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPageFileReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PageFileReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PageFileReplyValidationError{}

// Validate checks the field values on UpdateFileRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UpdateFileRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateFileRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateFileRequestMultiError, or nil if none found.
func (m *UpdateFileRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateFileRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := UpdateFileRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetApp()) < 1 {
		err := UpdateFileRequestValidationError{
			field:  "App",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := UpdateFileRequestValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetDirectoryId() <= 0 {
		err := UpdateFileRequestValidationError{
			field:  "DirectoryId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return UpdateFileRequestMultiError(errors)
	}

	return nil
}

// UpdateFileRequestMultiError is an error wrapping multiple validation errors
// returned by UpdateFileRequest.ValidateAll() if the designated constraints
// aren't met.
type UpdateFileRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateFileRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateFileRequestMultiError) AllErrors() []error { return m }

// UpdateFileRequestValidationError is the validation error returned by
// UpdateFileRequest.Validate if the designated constraints aren't met.
type UpdateFileRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateFileRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateFileRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateFileRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateFileRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateFileRequestValidationError) ErrorName() string {
	return "UpdateFileRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateFileRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateFileRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateFileRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateFileRequestValidationError{}

// Validate checks the field values on DeleteFileRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DeleteFileRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteFileRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteFileRequestMultiError, or nil if none found.
func (m *DeleteFileRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteFileRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetIds()) < 1 {
		err := DeleteFileRequestValidationError{
			field:  "Ids",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetApp()) < 1 {
		err := DeleteFileRequestValidationError{
			field:  "App",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetDirectoryId() <= 0 {
		err := DeleteFileRequestValidationError{
			field:  "DirectoryId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DeleteFileRequestMultiError(errors)
	}

	return nil
}

// DeleteFileRequestMultiError is an error wrapping multiple validation errors
// returned by DeleteFileRequest.ValidateAll() if the designated constraints
// aren't met.
type DeleteFileRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteFileRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteFileRequestMultiError) AllErrors() []error { return m }

// DeleteFileRequestValidationError is the validation error returned by
// DeleteFileRequest.Validate if the designated constraints aren't met.
type DeleteFileRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteFileRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteFileRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteFileRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteFileRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteFileRequestValidationError) ErrorName() string {
	return "DeleteFileRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteFileRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteFileRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteFileRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteFileRequestValidationError{}

// Validate checks the field values on UploadFileRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UploadFileRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UploadFileRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UploadFileRequestMultiError, or nil if none found.
func (m *UploadFileRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UploadFileRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetData()) < 0 {
		err := UploadFileRequestValidationError{
			field:  "Data",
			reason: "value length must be at least 0 bytes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetUploadId()) < 1 {
		err := UploadFileRequestValidationError{
			field:  "UploadId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetIndex() <= 0 {
		err := UploadFileRequestValidationError{
			field:  "Index",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return UploadFileRequestMultiError(errors)
	}

	return nil
}

// UploadFileRequestMultiError is an error wrapping multiple validation errors
// returned by UploadFileRequest.ValidateAll() if the designated constraints
// aren't met.
type UploadFileRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UploadFileRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UploadFileRequestMultiError) AllErrors() []error { return m }

// UploadFileRequestValidationError is the validation error returned by
// UploadFileRequest.Validate if the designated constraints aren't met.
type UploadFileRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UploadFileRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UploadFileRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UploadFileRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UploadFileRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UploadFileRequestValidationError) ErrorName() string {
	return "UploadFileRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UploadFileRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUploadFileRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UploadFileRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UploadFileRequestValidationError{}

// Validate checks the field values on UploadFileReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UploadFileReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UploadFileReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UploadFileReplyMultiError, or nil if none found.
func (m *UploadFileReply) ValidateAll() error {
	return m.validate(true)
}

func (m *UploadFileReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Src

	// no validation rules for Sha

	if len(errors) > 0 {
		return UploadFileReplyMultiError(errors)
	}

	return nil
}

// UploadFileReplyMultiError is an error wrapping multiple validation errors
// returned by UploadFileReply.ValidateAll() if the designated constraints
// aren't met.
type UploadFileReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UploadFileReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UploadFileReplyMultiError) AllErrors() []error { return m }

// UploadFileReplyValidationError is the validation error returned by
// UploadFileReply.Validate if the designated constraints aren't met.
type UploadFileReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UploadFileReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UploadFileReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UploadFileReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UploadFileReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UploadFileReplyValidationError) ErrorName() string { return "UploadFileReplyValidationError" }

// Error satisfies the builtin error interface
func (e UploadFileReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUploadFileReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UploadFileReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UploadFileReplyValidationError{}
