// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.3
// - protoc             v4.24.4
// source: api/file/proto/file_service.proto

package file

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationFileDeleteUserFile = "/resource.api.file.File/DeleteUserFile"
const OperationFileGetUserFile = "/resource.api.file.File/GetUserFile"
const OperationFileListUserFile = "/resource.api.file.File/ListUserFile"
const OperationFilePrepareUploadFile = "/resource.api.file.File/PrepareUploadFile"
const OperationFileUpdateUserFile = "/resource.api.file.File/UpdateUserFile"

type FileHTTPServer interface {
	// DeleteUserFile DeleteUserFile 删除文件信息
	DeleteUserFile(context.Context, *DeleteUserFileRequest) (*DeleteUserFileReply, error)
	// GetUserFile GetFile 获取指定的文件信息
	GetUserFile(context.Context, *GetUserFileRequest) (*GetUserFileReply, error)
	// ListUserFile ListUserFile 获取文件信息列表
	ListUserFile(context.Context, *ListUserFileRequest) (*ListUserFileReply, error)
	// PrepareUploadFile PrepareUploadFile 预上传文件信息
	PrepareUploadFile(context.Context, *PrepareUploadFileRequest) (*PrepareUploadFileReply, error)
	// UpdateUserFile UpdateFile 更新文件信息
	UpdateUserFile(context.Context, *UpdateUserFileRequest) (*UpdateUserFileReply, error)
}

func RegisterFileHTTPServer(s *http.Server, srv FileHTTPServer) {
	r := s.Route("/")
	r.GET("/resource/api/user/file", _File_GetUserFile0_HTTP_Handler(srv))
	r.GET("/resource/api/files", _File_ListUserFile0_HTTP_Handler(srv))
	r.POST("/resource/client/file/prepare_upload", _File_PrepareUploadFile0_HTTP_Handler(srv))
	r.POST("/resource/api/file/prepare_upload", _File_PrepareUploadFile1_HTTP_Handler(srv))
	r.PUT("/resource/api/file", _File_UpdateUserFile0_HTTP_Handler(srv))
	r.DELETE("/resource/api/file", _File_DeleteUserFile0_HTTP_Handler(srv))
}

func _File_GetUserFile0_HTTP_Handler(srv FileHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserFileRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileGetUserFile)
		h := ctx.Middleware(func(ctx context.Context, req any) (any, error) {
			return srv.GetUserFile(ctx, req.(*GetUserFileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUserFileReply)
		return ctx.Result(200, reply)
	}
}

func _File_ListUserFile0_HTTP_Handler(srv FileHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListUserFileRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileListUserFile)
		h := ctx.Middleware(func(ctx context.Context, req any) (any, error) {
			return srv.ListUserFile(ctx, req.(*ListUserFileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListUserFileReply)
		return ctx.Result(200, reply)
	}
}

func _File_PrepareUploadFile0_HTTP_Handler(srv FileHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PrepareUploadFileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFilePrepareUploadFile)
		h := ctx.Middleware(func(ctx context.Context, req any) (any, error) {
			return srv.PrepareUploadFile(ctx, req.(*PrepareUploadFileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PrepareUploadFileReply)
		return ctx.Result(200, reply)
	}
}

func _File_PrepareUploadFile1_HTTP_Handler(srv FileHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PrepareUploadFileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFilePrepareUploadFile)
		h := ctx.Middleware(func(ctx context.Context, req any) (any, error) {
			return srv.PrepareUploadFile(ctx, req.(*PrepareUploadFileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PrepareUploadFileReply)
		return ctx.Result(200, reply)
	}
}

func _File_UpdateUserFile0_HTTP_Handler(srv FileHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateUserFileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileUpdateUserFile)
		h := ctx.Middleware(func(ctx context.Context, req any) (any, error) {
			return srv.UpdateUserFile(ctx, req.(*UpdateUserFileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateUserFileReply)
		return ctx.Result(200, reply)
	}
}

func _File_DeleteUserFile0_HTTP_Handler(srv FileHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteUserFileRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileDeleteUserFile)
		h := ctx.Middleware(func(ctx context.Context, req any) (any, error) {
			return srv.DeleteUserFile(ctx, req.(*DeleteUserFileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteUserFileReply)
		return ctx.Result(200, reply)
	}
}

type FileHTTPClient interface {
	DeleteUserFile(ctx context.Context, req *DeleteUserFileRequest, opts ...http.CallOption) (rsp *DeleteUserFileReply, err error)
	GetUserFile(ctx context.Context, req *GetUserFileRequest, opts ...http.CallOption) (rsp *GetUserFileReply, err error)
	ListUserFile(ctx context.Context, req *ListUserFileRequest, opts ...http.CallOption) (rsp *ListUserFileReply, err error)
	PrepareUploadFile(ctx context.Context, req *PrepareUploadFileRequest, opts ...http.CallOption) (rsp *PrepareUploadFileReply, err error)
	UpdateUserFile(ctx context.Context, req *UpdateUserFileRequest, opts ...http.CallOption) (rsp *UpdateUserFileReply, err error)
}

type FileHTTPClientImpl struct {
	cc *http.Client
}

func NewFileHTTPClient(client *http.Client) FileHTTPClient {
	return &FileHTTPClientImpl{client}
}

func (c *FileHTTPClientImpl) DeleteUserFile(ctx context.Context, in *DeleteUserFileRequest, opts ...http.CallOption) (*DeleteUserFileReply, error) {
	var out DeleteUserFileReply
	pattern := "/resource/api/file"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationFileDeleteUserFile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *FileHTTPClientImpl) GetUserFile(ctx context.Context, in *GetUserFileRequest, opts ...http.CallOption) (*GetUserFileReply, error) {
	var out GetUserFileReply
	pattern := "/resource/api/user/file"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationFileGetUserFile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *FileHTTPClientImpl) ListUserFile(ctx context.Context, in *ListUserFileRequest, opts ...http.CallOption) (*ListUserFileReply, error) {
	var out ListUserFileReply
	pattern := "/resource/api/files"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationFileListUserFile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *FileHTTPClientImpl) PrepareUploadFile(ctx context.Context, in *PrepareUploadFileRequest, opts ...http.CallOption) (*PrepareUploadFileReply, error) {
	var out PrepareUploadFileReply
	pattern := "/resource/api/file/prepare_upload"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationFilePrepareUploadFile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *FileHTTPClientImpl) UpdateUserFile(ctx context.Context, in *UpdateUserFileRequest, opts ...http.CallOption) (*UpdateUserFileReply, error) {
	var out UpdateUserFileReply
	pattern := "/resource/api/file"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationFileUpdateUserFile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
