
env: TEST
server:
  http:
    host: 127.0.0.1
    port: 7003
    timeout: 10s
    marshal:
      emitUnpopulated: true
      useProtoNames: true
  grpc:
    host: 127.0.0.1
    port: 8003
    timeout: 10s
log:
  level: 0
  output:
    - stdout
    - file
  file:
    name: ./tmp/runtime/output.log
    maxSize: 1
    maxBackup: 5
    maxAge: 1
    compress: false
database:
  system:
    enable: true #是否启用数据库
    drive: mysql #数据库类型
    autoCreate: true #是否自动创建数据库
    connect:
      username: root
      password: root
      host: 127.0.0.1
      port: 3306
      dbName: resource
      option: ?charset=utf8mb4&parseTime=True&loc=Local
    config:
      transformError:
        enable: true
      initializer:
        enable: true
        path: deploy/data.sql
      maxLifetime: 2h #最大生存时间
      maxOpenConn: 20 #最大连接数量
      maxIdleConn: 10 #最大空闲数量
      logLevel: 4 #日志等级
      slowThreshold: 2s #慢sql阈值
business:
  storage:
    type: local
    serverPath: /resource/v1/static
    localDir: static
    maxSingularSize: 400
    maxChunkSize: 200
    maxChunkCount: 200
    acceptTypes: ["jpg","png","txt","ppt","pptx","mp4"]
  export:
    localDir: static/export
    expire: 3d
logging:
  enable: true