// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.3
// - protoc             v4.24.4
// source: api/entity/proto/entity_service.proto

package entity

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationEntityLoadEntity = "/resource.api.entity.Entity/LoadEntity"

type EntityHTTPServer interface {
	// LoadEntity LoadEntity 载入全部系统的实体
	LoadEntity(context.Context, *emptypb.Empty) (*LoadEntityReply, error)
}

func RegisterEntityHTTPServer(s *http.Server, srv EntityHTTPServer) {
	r := s.Route("/")
	r.GET("/resource/api/v1/load/entities", _Entity_LoadEntity0_HTTP_Handler(srv))
}

func _Entity_LoadEntity0_HTTP_Handler(srv EntityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEntityLoadEntity)
		h := ctx.Middleware(func(ctx context.Context, req any) (any, error) {
			return srv.LoadEntity(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LoadEntityReply)
		return ctx.Result(200, reply)
	}
}

type EntityHTTPClient interface {
	LoadEntity(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *LoadEntityReply, err error)
}

type EntityHTTPClientImpl struct {
	cc *http.Client
}

func NewEntityHTTPClient(client *http.Client) EntityHTTPClient {
	return &EntityHTTPClientImpl{client}
}

func (c *EntityHTTPClientImpl) LoadEntity(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*LoadEntityReply, error) {
	var out LoadEntityReply
	pattern := "/resource/api/v1/load/entities"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEntityLoadEntity))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
