// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/entity/proto/entity.proto

package entity

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on LoadEntityReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *LoadEntityReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LoadEntityReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// LoadEntityReplyMultiError, or nil if none found.
func (m *LoadEntityReply) ValidateAll() error {
	return m.validate(true)
}

func (m *LoadEntityReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Total

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, LoadEntityReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, LoadEntityReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return LoadEntityReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return LoadEntityReplyMultiError(errors)
	}

	return nil
}

// LoadEntityReplyMultiError is an error wrapping multiple validation errors
// returned by LoadEntityReply.ValidateAll() if the designated constraints
// aren't met.
type LoadEntityReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LoadEntityReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LoadEntityReplyMultiError) AllErrors() []error { return m }

// LoadEntityReplyValidationError is the validation error returned by
// LoadEntityReply.Validate if the designated constraints aren't met.
type LoadEntityReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LoadEntityReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LoadEntityReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LoadEntityReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LoadEntityReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LoadEntityReplyValidationError) ErrorName() string { return "LoadEntityReplyValidationError" }

// Error satisfies the builtin error interface
func (e LoadEntityReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLoadEntityReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LoadEntityReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LoadEntityReplyValidationError{}

// Validate checks the field values on LoadEntityReply_EntityField with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *LoadEntityReply_EntityField) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LoadEntityReply_EntityField with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// LoadEntityReply_EntityFieldMultiError, or nil if none found.
func (m *LoadEntityReply_EntityField) ValidateAll() error {
	return m.validate(true)
}

func (m *LoadEntityReply_EntityField) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Comment

	if len(errors) > 0 {
		return LoadEntityReply_EntityFieldMultiError(errors)
	}

	return nil
}

// LoadEntityReply_EntityFieldMultiError is an error wrapping multiple
// validation errors returned by LoadEntityReply_EntityField.ValidateAll() if
// the designated constraints aren't met.
type LoadEntityReply_EntityFieldMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LoadEntityReply_EntityFieldMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LoadEntityReply_EntityFieldMultiError) AllErrors() []error { return m }

// LoadEntityReply_EntityFieldValidationError is the validation error returned
// by LoadEntityReply_EntityField.Validate if the designated constraints
// aren't met.
type LoadEntityReply_EntityFieldValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LoadEntityReply_EntityFieldValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LoadEntityReply_EntityFieldValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LoadEntityReply_EntityFieldValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LoadEntityReply_EntityFieldValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LoadEntityReply_EntityFieldValidationError) ErrorName() string {
	return "LoadEntityReply_EntityFieldValidationError"
}

// Error satisfies the builtin error interface
func (e LoadEntityReply_EntityFieldValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLoadEntityReply_EntityField.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LoadEntityReply_EntityFieldValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LoadEntityReply_EntityFieldValidationError{}

// Validate checks the field values on LoadEntityReply_Entity with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *LoadEntityReply_Entity) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LoadEntityReply_Entity with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// LoadEntityReply_EntityMultiError, or nil if none found.
func (m *LoadEntityReply_Entity) ValidateAll() error {
	return m.validate(true)
}

func (m *LoadEntityReply_Entity) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Database

	// no validation rules for Name

	// no validation rules for Comment

	for idx, item := range m.GetFields() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, LoadEntityReply_EntityValidationError{
						field:  fmt.Sprintf("Fields[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, LoadEntityReply_EntityValidationError{
						field:  fmt.Sprintf("Fields[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return LoadEntityReply_EntityValidationError{
					field:  fmt.Sprintf("Fields[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return LoadEntityReply_EntityMultiError(errors)
	}

	return nil
}

// LoadEntityReply_EntityMultiError is an error wrapping multiple validation
// errors returned by LoadEntityReply_Entity.ValidateAll() if the designated
// constraints aren't met.
type LoadEntityReply_EntityMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LoadEntityReply_EntityMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LoadEntityReply_EntityMultiError) AllErrors() []error { return m }

// LoadEntityReply_EntityValidationError is the validation error returned by
// LoadEntityReply_Entity.Validate if the designated constraints aren't met.
type LoadEntityReply_EntityValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LoadEntityReply_EntityValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LoadEntityReply_EntityValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LoadEntityReply_EntityValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LoadEntityReply_EntityValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LoadEntityReply_EntityValidationError) ErrorName() string {
	return "LoadEntityReply_EntityValidationError"
}

// Error satisfies the builtin error interface
func (e LoadEntityReply_EntityValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLoadEntityReply_Entity.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LoadEntityReply_EntityValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LoadEntityReply_EntityValidationError{}
