// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.24.4
// source: api/entity/proto/entity.proto

package entity

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoadEntityReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total uint32                    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List  []*LoadEntityReply_Entity `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *LoadEntityReply) Reset() {
	*x = LoadEntityReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_entity_proto_entity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadEntityReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadEntityReply) ProtoMessage() {}

func (x *LoadEntityReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_entity_proto_entity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadEntityReply.ProtoReflect.Descriptor instead.
func (*LoadEntityReply) Descriptor() ([]byte, []int) {
	return file_api_entity_proto_entity_proto_rawDescGZIP(), []int{0}
}

func (x *LoadEntityReply) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *LoadEntityReply) GetList() []*LoadEntityReply_Entity {
	if x != nil {
		return x.List
	}
	return nil
}

type LoadEntityReply_EntityField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Comment string `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *LoadEntityReply_EntityField) Reset() {
	*x = LoadEntityReply_EntityField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_entity_proto_entity_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadEntityReply_EntityField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadEntityReply_EntityField) ProtoMessage() {}

func (x *LoadEntityReply_EntityField) ProtoReflect() protoreflect.Message {
	mi := &file_api_entity_proto_entity_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadEntityReply_EntityField.ProtoReflect.Descriptor instead.
func (*LoadEntityReply_EntityField) Descriptor() ([]byte, []int) {
	return file_api_entity_proto_entity_proto_rawDescGZIP(), []int{0, 0}
}

func (x *LoadEntityReply_EntityField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoadEntityReply_EntityField) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type LoadEntityReply_Entity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Database string                         `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Name     string                         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Comment  string                         `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	Fields   []*LoadEntityReply_EntityField `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *LoadEntityReply_Entity) Reset() {
	*x = LoadEntityReply_Entity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_entity_proto_entity_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadEntityReply_Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadEntityReply_Entity) ProtoMessage() {}

func (x *LoadEntityReply_Entity) ProtoReflect() protoreflect.Message {
	mi := &file_api_entity_proto_entity_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadEntityReply_Entity.ProtoReflect.Descriptor instead.
func (*LoadEntityReply_Entity) Descriptor() ([]byte, []int) {
	return file_api_entity_proto_entity_proto_rawDescGZIP(), []int{0, 1}
}

func (x *LoadEntityReply_Entity) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *LoadEntityReply_Entity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoadEntityReply_Entity) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *LoadEntityReply_Entity) GetFields() []*LoadEntityReply_EntityField {
	if x != nil {
		return x.Fields
	}
	return nil
}

var File_api_entity_proto_entity_proto protoreflect.FileDescriptor

var file_api_entity_proto_entity_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x13, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc4, 0x02,
	0x0a, 0x0f, 0x4c, 0x6f, 0x61, 0x64, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x3f, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x4c, 0x6f, 0x61, 0x64,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x45, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0x3b, 0x0a, 0x0b, 0x45, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0x9c, 0x01, 0x0a, 0x06, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x48, 0x0a, 0x06, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x42, 0x2b, 0x0a, 0x13, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x42, 0x08, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x56, 0x31, 0x50, 0x01, 0x5a, 0x08, 0x2e, 0x3b, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_entity_proto_entity_proto_rawDescOnce sync.Once
	file_api_entity_proto_entity_proto_rawDescData = file_api_entity_proto_entity_proto_rawDesc
)

func file_api_entity_proto_entity_proto_rawDescGZIP() []byte {
	file_api_entity_proto_entity_proto_rawDescOnce.Do(func() {
		file_api_entity_proto_entity_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_entity_proto_entity_proto_rawDescData)
	})
	return file_api_entity_proto_entity_proto_rawDescData
}

var file_api_entity_proto_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_entity_proto_entity_proto_goTypes = []interface{}{
	(*LoadEntityReply)(nil),             // 0: resource.api.entity.LoadEntityReply
	(*LoadEntityReply_EntityField)(nil), // 1: resource.api.entity.LoadEntityReply.EntityField
	(*LoadEntityReply_Entity)(nil),      // 2: resource.api.entity.LoadEntityReply.Entity
}
var file_api_entity_proto_entity_proto_depIdxs = []int32{
	2, // 0: resource.api.entity.LoadEntityReply.list:type_name -> resource.api.entity.LoadEntityReply.Entity
	1, // 1: resource.api.entity.LoadEntityReply.Entity.fields:type_name -> resource.api.entity.LoadEntityReply.EntityField
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_entity_proto_entity_proto_init() }
func file_api_entity_proto_entity_proto_init() {
	if File_api_entity_proto_entity_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_entity_proto_entity_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadEntityReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_entity_proto_entity_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadEntityReply_EntityField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_entity_proto_entity_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadEntityReply_Entity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_entity_proto_entity_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_entity_proto_entity_proto_goTypes,
		DependencyIndexes: file_api_entity_proto_entity_proto_depIdxs,
		MessageInfos:      file_api_entity_proto_entity_proto_msgTypes,
	}.Build()
	File_api_entity_proto_entity_proto = out.File
	file_api_entity_proto_entity_proto_rawDesc = nil
	file_api_entity_proto_entity_proto_goTypes = nil
	file_api_entity_proto_entity_proto_depIdxs = nil
}
